### List vs Arrays
- List can have multiple datatypes
- Array can have only one datatypes

In [4]:
import numpy as np
import matplotlib.pyplot as plt

#### Lists

In [10]:
# Lists
listA = ['a',123,'orange',4.5,'apple']
# List indexing
print(listA[0])

# Slicing
print(listA[0:2])

a
['a', 123]


In [19]:
# Lists can append items in place
listA.append('studying')
listA

['a', 123, 'orange', 4.5, 'apple', 'studying']

#### Arrays

In [11]:
# Arrays:
arrayA = np.array([1,4,5,6,7]) # take a list of integer
arrayB = np.array([1.3,4.5,6.8,8.9]) # take a tuple of floats
arrayC = np.array(['an','fv','cd','dfg']) # take a list of strings 

print(arrayA)
print(arrayB)
print(arrayC)

[1 4 5 6 7]
[1.3 4.5 6.8 8.9]
['an' 'fv' 'cd' 'dfg']


In [12]:
# more than one dimension arrays
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [14]:
# use minimum dimension of 3
np.array([3.4,5.6,7.0],ndmin=3)

array([[[3.4, 5.6, 7. ]]])

In [16]:
# Use the type provided to create an array
np.array([3.5,5.4,6.7],dtype=int)

array([3, 5, 6])

In [17]:
np.array((2,3.4,3.3),dtype=complex)

array([2. +0.j, 3.4+0.j, 3.3+0.j])

In [18]:
# Do calculations with numpy arrays
arrayA/3

array([0.33333333, 1.33333333, 1.66666667, 2.        , 2.33333333])

In [21]:
# Append an item to array
array1 = np.array([3.4,5.6,7.2])
print(array1)
np.append(array1,4.0) # This will not work since cannot append in place for arrays
print(array1)

# The correct way to append an array is
array1 = np.append(array1,5.4)
print(array1)

[3.4 5.6 7.2]
[3.4 5.6 7.2]
[3.4 5.6 7.2 5.4]
